#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

pip install --root-user-action=ignore -r requirements/local_extra.txt
python manage.py migrate
exec python manage.py runserver_plus 0.0.0.0:8000
