# Config for Dependabot updates. See Documentation here:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: 'github-actions'
    target-branch: 'develop'
    directory: '/'
    # Every weekday
    schedule:
      interval: 'daily'

  # Enable version updates for Docker
  # We need to specify each Dockerfile in a separate entry because Dependabot doesn't
  # support wildcards or recursively checking subdirectories. Check this issue for updates:
  # https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `compose/local/django` directory
    target-branch: 'develop'
    directory: 'compose/local/django/'
    # Every weekday
    schedule:
      interval: 'daily'
    # Ignore minor version updates (3.10 -> 3.11) but update patch versions
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'

  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `compose/local/docs` directory
    target-branch: 'develop'
    directory: 'compose/local/docs/'
    # Every weekday
    schedule:
      interval: 'daily'
    # Ignore minor version updates (3.10 -> 3.11) but update patch versions
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'

  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `compose/production/django` directory
    target-branch: 'develop'
    directory: 'compose/production/django/'
    # Every weekday
    schedule:
      interval: 'daily'
    # Ignore minor version updates (3.10 -> 3.11) but update patch versions
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'

  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `compose/production/postgres` directory
    target-branch: 'develop'
    directory: 'compose/production/postgres/'
    # Every weekday
    schedule:
      interval: 'daily'

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: 'pip'
    # Look for a `requirements.txt` in the `root` directory
    # also 'setup.cfg', 'runtime.txt' and 'requirements/*.txt'
    target-branch: 'develop'
    directory: 'requirements/'
    # Every weekday
    schedule:
      interval: 'daily'
