volumes:
  spade_production_django_media: {}
  spade_production_postgres_data: {}

services:
  spade:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: ghcr.io/crugroup/spade:latest
    container_name: spade_production
    volumes:
      - spade_production_django_media:/app/spadeapp/media
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - '8000:5000'

  spadeui:
    image: ghcr.io/crugroup/spadeui:latest
    container_name: spadeui_production
    depends_on:
      - spade
    ports:
      - '3000:80'

  postgres:
    image: postgres:16
    volumes:
      - spade_production_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.production/.postgres
