version: '3'

volumes:
  production_django_media: {}
  production_postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: spadeapp_production_django
    volumes:
      - production_django_media:/app/spadeapp/media
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - '8000:5000'
  
  spadeui:
    image: ghcr.io/crugroup/spadeui:develop
    container_name: spadeapp_production_spadeui
    depends_on:
      - django
    ports:
      - '3000:80'

  postgres:
    image: postgres:16
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.production/.postgres
