# Generated by Django 4.2.7 on 2023-12-04 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx"),
        ("processes", "0002_alter_processrun_result"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("system_params", models.JSONField(blank=True, null=True)),
                ("user_params", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-pk",),
            },
        ),
        migrations.CreateModel(
            name="FileFormat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("format", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="FileProcessor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("processor", models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=256)),
                (
                    "result",
                    models.CharField(
                        choices=[("success", "Success"), ("warning", "Warning"), ("failed", "Failed")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("system_params", models.JSONField(blank=True, null=True)),
                ("user_params", models.JSONField(blank=True, null=True)),
                ("output", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="files.file")),
                (
                    "linked_process_run",
                    models.OneToOneField(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="processes.processrun"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-pk",),
            },
        ),
        migrations.AddField(
            model_name="file",
            name="format",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="files.fileformat"),
        ),
        migrations.AddField(
            model_name="file",
            name="linked_process",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="processes.process"
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="processor",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="files.fileprocessor"),
        ),
        migrations.AddField(
            model_name="file",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
