# Generated by Django 5.2.2 on 2025-06-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_file_variable_sets"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileformat",
            name="frictionless_schema",
            field=models.JSONField(
                blank=True,
                help_text="Frictionless data schema for validating files of this format",
                null=True,
            ),
        ),
    ]
