# Generated by Django 6.1.1 on 2026-09-29 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_fileformat_frictionless_schema'),
        ('processes', '0004_processrun_processrun_process_id_desc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fileupload',
            index=models.Index(fields=['file', '-id'], name='fileupload_file_id_desc'),
        ),
    ]
