# Generated by Django 5.2.2 on 2025-06-10 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="processvariablesets",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="processvariablesets",
            name="process",
        ),
        migrations.RemoveField(
            model_name="processvariablesets",
            name="variable_set",
        ),
        migrations.DeleteModel(
            name="FileVariableSets",
        ),
        migrations.DeleteModel(
            name="ProcessVariableSets",
        ),
    ]
