# Generated by Django 5.0.3 on 2024-04-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="executor",
            options={"ordering": ("-pk",)},
        ),
    ]
