# Generated by Django 5.2.2 on 2025-06-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processes", "0002_alter_executor_options"),
        ("variables", "0002_alter_processvariablesets_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="variable_sets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Variable sets to be used by the process",
                to="variables.variableset",
            ),
        ),
    ]
