# Generated by Django 6.1.1 on 2026-09-29 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_process_variable_sets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='processrun',
            index=models.Index(fields=['process', '-id'], name='processrun_process_id_desc'),
        ),
    ]
