#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

print_help() {
    echo "Usage: $0 [migrate|start|help|<custom command>]"
    echo
    echo "Commands:"
    echo "  migrate           Run Django migrations"
    echo "  start             Run Django server (default)"
    echo "  help              Show this help message"
    echo "  <custom command>  Run any command in the container"
}

# Default to "start" when no args are given
if [ "$#" -eq 0 ]; then
    set -- start
fi

source /wait_for_postgres.sh

case "$1" in
    migrate)
        shift
        exec python /app/manage.py migrate --noinput "$@"
        ;;
    start)
        shift
        /start "$@"
        ;;
    help|-h|--help)
        print_help
        ;;
    *)
        # Passthrough for arbitrary commands, e.g.:
        # docker run image python /app/manage.py shell
        exec "$@"
        ;;
esac
